#ifndef CUSTOMER_H_
#define CUSTOMER_H_

#include <fstream.h>
#include <conio.h>
#include <stdio.h>
#include <string.h>
#include <dos.h>

using namespace std;

class CUSTOMER
{
	int R_No;
	char name[10];
	char add[20];
	char phone[10];
	int dd, mm, yy;
	int daysStayed;
	long amount;

public:
	void intro();
	void inquiryRoomNo();
	void inquiryCust();
	void check_in();
	void check_out();
	void reports();
};

void CUSTOMER::intro()
{
	clrscr();
	box(8, 4, 72, 23, 0);
	gotoxy(26, 2);
	cout << "H O T E L   M A N A G E M E N T";
	gotoxy(29, 7);
	cout << "~~I N T R O D U C T I O N~~";
	gotoxy(11, 9);
	cout << "This 'HOTEL MANAGEMENT SYSTEM' Project is  designed for a ";
	gotoxy(11, 10);
	cout << "hotel in which you can generate and manage a simple database";
	gotoxy(11, 11);
	cout << "for rooms.";
	gotoxy(11, 12);
	cout << "The room number is automatically generated by the software ";
	gotoxy(11, 13);
	cout << "and is stored in a binary file by the name 'ROOMS'. This data";
	gotoxy(11, 14);
	cout << "base is  basically  used as a MASTER file to be used as a";
	gotoxy(11, 15);
	cout << "look-up table for information like Room Charges, Type of";
	gotoxy(11, 16);
	cout << "Room, either 'Deluxe' or 'Ordinary' and the status of";
	gotoxy(11, 17);
	cout << "the room,Vacant or Occupied.";
	gotoxy(11, 18);
	cout << "In this software you can ask for an inquiry on the basis of";
	gotoxy(11, 19);
	cout << "the Room No. or the Customer's Name. Reports are designed on";
	gotoxy(11, 20);
	cout << "the basis of the 'CUST' file to give the detail of the";
	gotoxy(11, 21);
	cout << "cusomer's stay and Payments made by the customer.";
	gotoxy(28, 25);
	cout << "<Press any key to continue>";
	getch();
}

void CUSTOMER::inquiryRoomNo()
{
	clrscr();
	int flag = 0;
	char NAME[10];
	box(25, 10, 65, 16, 0);
	gotoxy(25, 7);
	cout << "I N Q U I R I N G   R O O M   N U M B E R";
	gotoxy(30, 13);
	cout << "Enter Customer's Name : ";
	gets(NAME);

	CUSTOMER c;
	fstream fin("cust", ios::binary | ios::in);
	while (fin.read((char *)&c, sizeof(c)))
	{
		if (strcmpi(NAME, c.name) == 0)
		{
			flag = 1;
			clrscr();
			box(21, 3, 59, 19, 1);
			gotoxy(24, 5);
			cout << "C U S T O M E R ' S   D E T A I L S";
			gotoxy(29, 9);
			cout << "Room Number   : " << c.R_No;
			gotoxy(29, 11);
			cout << "Customer Name : " << c.name;
			gotoxy(29, 13);
			cout << "Address       : " << c.add;
			gotoxy(29, 15);
			cout << "Phone No.     : " << c.phone;
			gotoxy(29, 17);
			cout << "Check-in      : " << c.dd << "/" << c.mm << "/" << c.yy;
			break;
		}
	}
	fin.close();
	if (flag == 0)
	{
		clrscr();
		box(25, 10, 65, 16, 0);
		gotoxy(32, 13);
		cout << "No such Name Found !!!";
	}

	getch();
}

void CUSTOMER::inquiryCust()
{
	clrscr();
	int RNO, flag = 0;
	box(21, 10, 69, 16, 0);
	gotoxy(21, 7);
	cout << "I N Q U I R I N G   C U S T O M E R ' S   N A M E";
	gotoxy(35, 13);
	cout << "Enter Room Number : ";
	cin >> RNO;

	CUSTOMER c;
	fstream fin("cust", ios::binary | ios::in);
	while (fin.read((char *)&c, sizeof(c)))
	{
		if (RNO == c.R_No)
		{
			flag = 1;
			clrscr();
			box(21, 3, 59, 19, 1);
			gotoxy(24, 5);
			cout << "C U S T O M E R ' S   D E T A I L";
			gotoxy(29, 9);
			cout << "Room Number   : " << c.R_No;
			gotoxy(29, 11);
			cout << "Customer Name : " << c.name;
			gotoxy(29, 13);
			cout << "Address       : " << c.add;
			gotoxy(29, 15);
			cout << "Phone No.     : " << c.phone;
			gotoxy(29, 17);
			cout << "Check-in      : " << c.dd << "/" << c.mm << "/" << c.yy;
			break;
		}
	}
	fin.close();
	if (flag == 0)
	{
		clrscr();
		box(25, 10, 65, 16, 0);
		gotoxy(30, 13);
		cout << "No such Room No. Found !!!";
	}

	getch();
}

void CUSTOMER::check_in()
{
	clrscr();
	int TYPE, RNO, flag;
	ROOMS r;
	box(25, 9, 55, 22, 0);
	gotoxy(33, 11);
	cout << "C H E C K   I N";
	;
	gotoxy(20, 24);
	cout << "<Enter '1' for Deluxe and '0' for Ordinary>";
	gotoxy(31, 14);
	cout << "Enter Room Type : ";
	cin >> TYPE;
	if (TYPE != 0 && TYPE != 1)
	{
		while (TYPE != 0 && TYPE != 1)
		{
			gotoxy(20, 24);
			clreol();
			gotoxy(20, 24);
			cout << "ERROR!! ENTER AGAIN!!";
			gotoxy(31, 14);
			clreol();
			gotoxy(31, 14);
			cout << "Enter Room Type : ";
			cin >> TYPE;
		}
	}
	gotoxy(20, 24);
	clreol();

	RNO = r.findRoomNo(TYPE);

	gotoxy(20, 24);
	clreol();
	if (RNO == -1)
	{
		cout << "   This Room Type is not available !!!";
		getch();
		return;
	}
	else if (RNO == 0)
	{
		cout << "        Invalid room number !!!";
		getch();
		return;
	}
	else
	{
		CUSTOMER c;
		char NAME[10], ADD[20], PHONE[10];
		fstream fout("cust", ios::binary | ios::app);
		gotoxy(31, 16);
		cout << "Enter the Name  : ";
		gets(NAME);
		gotoxy(31, 18);
		cout << "Enter Address   : ";
		gets(ADD);
		gotoxy(31, 20);
		cout << "Enter Phone No. : ";
		gets(PHONE);

		c.R_No = RNO;
		c.daysStayed = -1;
		c.amount = -1;
		strcpy(c.name, NAME);
		strcpy(c.add, ADD);
		strcpy(c.phone, PHONE);
		c.dd = DD;
		c.mm = MM;
		c.yy = YY;
		fout.write((char *)&c, sizeof(c));
		fout.close();
	}
	r.bookRoom(RNO);
}

void CUSTOMER::check_out()
{
	clrscr();
	int RNO, flag = 0, AMOUNT;
	box(20, 9, 60, 20, 0);
	gotoxy(32, 11);
	cout << "C H E C K   O U T";
	;
	gotoxy(23, 14);
	cout << "Enter Room No. to Vacate : ";
	cin >> RNO;

	CUSTOMER c;
	fstream fin("cust", ios::binary | ios::in);
	while (fin.read((char *)&c, sizeof(c)))
	{
		if (RNO == c.R_No)
		{
			flag = 1;
			break;
		}
	}
	fin.close();
	if (flag == 0)
	{
		gotoxy(28, 17);
		cout << "No such Room Number !!!";
		getch();
		return;
	}

	if (flag == 1)
	{
		ROOMS r;
		r.releaseRoom(RNO);
		AMOUNT = r.retRoomCharges(RNO);
	}

	fstream fin1("cust", ios::binary | ios::in);
	fstream fout1("temp", ios::binary | ios::out);
	while (fin1.read((char *)&c, sizeof(c)))
	{
		if (RNO == c.R_No && c.daysStayed == -1)
		{
			int D;
			gotoxy(23, 16);
			cout << "Enter No. of Days stayed : ";
			cin >> D;
			c.daysStayed = D;
			c.amount = D * AMOUNT;
			gotoxy(23, 18);
			cout << "Total Charges are Rupees : " << c.amount;
			fout1.write((char *)&c, sizeof(c));
		}
		else
			fout1.write((char *)&c, sizeof(c));
	}
	fin1.close();
	fout1.close();
	remove("cust");
	rename("temp", "cust");
	getch();
}

void CUSTOMER::reports()
{
	clrscr();
	CUSTOMER c;
	box(5, 3, 76, 23, 1);
	gotoxy(21, 5);
	cout << "C U S T O M E R   S T A Y   S U M M A R Y";
	int i = 11, AMOUNT = 0;
	fstream fin("cust", ios::binary | ios::in);
	gotoxy(7, 9);
	cout
		<< "R.No NAME       ADDRESS      AMOUNT    DT/OF CHECK-IN    DAYS STAYED";
	while (fin.read((char *)&c, sizeof(c)))
	{
		gotoxy(7, i);
		cout << c.R_No;
		gotoxy(12, i);
		cout << c.name;
		gotoxy(23, i);
		cout << c.add;
		gotoxy(37, i);
		if (c.amount == -1)
			cout << "N/A";
		else
		{
			cout << c.amount << "/=";
			AMOUNT = AMOUNT + c.amount;
		}
		gotoxy(50, i);
		cout << c.dd << "/" << c.mm << "/" << c.yy;
		gotoxy(68, i);
		if (c.daysStayed == -1)
			cout << "N/A";
		else
			cout << c.daysStayed;

		i++;
		if (i == 22)
		{
			i = 11;
			clrscr();
			box(5, 3, 76, 23, 1);
			gotoxy(21, 5);
			cout << "C U S T O M E R   S T A Y   S U M M A R Y";
			gotoxy(7, 9);
			cout << "R.No NAME       ADDRESS      AMOUNT";
			cout << "    DT/OF CHECK-IN    DAYS STAYED";
			gotoxy(28, 25);
			cout << "<Press any key to continue>";
			getch();
		}
	}

	gotoxy(27, 25);
	clreol();
	gotoxy(27, 25);
	cout << "< Net Amount Rs.: " << AMOUNT << "/= >";
	fin.close();
	getch();
}

#endif
